# Generated by Django 5.1.1 on 2024-10-06 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField(verbose_name=datetime.date(2024, 10, 6))),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
